# Generated by Django 5.1.4 on 2025-01-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='boards',
        ),
    ]
