# Generated by Django 5.1.4 on 2025-02-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='images',
            field=models.ManyToManyField(related_name='boards', to='app.image'),
        ),
        migrations.DeleteModel(
            name='BoardImage',
        ),
    ]
