# Generated by Django 5.1.4 on 2025-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_board_images_delete_boardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
